Document: fuse-google-drive
Title: Debian fuse-google-drive Manual
Author: <insert document author here>
Abstract: This manual describes what fuse-google-drive is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fuse-google-drive/fuse-google-drive.sgml.gz

Format: postscript
Files: /usr/share/doc/fuse-google-drive/fuse-google-drive.ps.gz

Format: text
Files: /usr/share/doc/fuse-google-drive/fuse-google-drive.text.gz

Format: HTML
Index: /usr/share/doc/fuse-google-drive/html/index.html
Files: /usr/share/doc/fuse-google-drive/html/*.html
